sonar.organization=denisndj
sonar.projectKey=DenisNDJ_OC_NDJANDADenis_Projet7
sonar.projectName=OC_NDJANDADenis_Projet7

# Analyse depuis la racine
sonar.sources=front,back

# Exclusions utiles
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.next/**,**/coverage/**,**/vendor/**

# Encodage
sonar.sourceEncoding=UTF-8