sonar.organization=denisndj
sonar.projectKey=DenisNDJ_OC_NDJANDADenis_Projet7
sonar.projectName=OC_NDJANDADenis_Projet7

# On analyse les 2 dossiers dans un seul projet
sonar.sources=front,back

# Exclusions utiles
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.next/**,**/coverage/**

sonar.sourceEncoding=UTF-8