name: CI (Test/Buildd/Release/SonarCloud)

on:
  push:

permissions:
  contents: read

jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Analyze front with SonarCloud
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.TOKEN_SONAR }}
        with:
          projectBaseDir: .
          args:
            -Dsonar.projectKey=DenisNDJ_OC_NDJANDADenis_Projet7
            -Dsonar.organization=denisndj

  test:
    needs: Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Dépendances Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Dépendances Node
        uses: actions/setup-node@v6
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: front/package-lock.json

      - name: Run tests
        run: bash ./run_all_test.sh

      - name: Test Report
        uses: dorny/test-reporter@v3
        if: ${{ !cancelled() }}
        with:
          name: Tests
          path: test_result/**/*.xml
          reporter: java-junit 
