name: CI (Test/Buildd/Release/SonarCloud)

on:
  push:

permissions:
  contents: read

jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Dépendances Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Dépendances Node
        uses: actions/setup-node@v6
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: front/package-lock.json

      - name: Install front dependencies
        working-directory: front
        run: npm ci

      - name: Build and test back
        working-directory: back
        run: chmod +x gradlew

      - name: Build and test back
        working-directory: back
        run: ./gradlew build

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.TOKEN_SONAR }}
        with:
          args: >
            -Dsonar.organization=denisndj
            -Dsonar.projectKey=DenisNDJ_OC_NDJANDADenis_Projet7
            -Dsonar.sources=front,back
            -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.next/**,**/coverage/**,**/*.java
  test:
    needs: Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Dépendances Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Dépendances Node
        uses: actions/setup-node@v6
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: front/package-lock.json

      - name: Run tests
        run: bash ./run_all_test.sh

      - name: Test Report
        uses: dorny/test-reporter@v3
        if: ${{ !cancelled() }}
        with:
          name: Tests
          path: test_result/**/*.xml
          reporter: java-junit 
